# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Border Crossings
email: andrew@andrewspencer.net
description: >
  Blog on Java programming and other matters (currently in an abandoned state).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewspencer.net" # the base hostname & protocol for your site
twitter_username: andrewspencer74

excerpt_separator: <!--more-->
permalink: /:year/:slug

# Build settings
markdown: kramdown
